#
# Alpine Dockerfile
#

# Pull base image.
FROM alpine:20200626

# Install.

# Add files.

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["sh"]

