#
# Busybox Dockerfile
#

# Pull base image.
FROM busybox:1.32.0

# Override default shell.
SHELL ["/bin/sh","-c"]

# Install.

# Add files.

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["busybox"]
